[features]
seeds = false

[programs.localnet]
master = "HtTGeeRqoJyF77y4fhadcAw7i1jbdugsV9iY3hYUNHLd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/giacomocavicchioli/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
